// 1           // true
// 0           // false
// -1          // true
// true        // true
// false       // false
// 'string'    // true
// null        // false
// undefined   // false
// []          // true